on:
  push:
    paths:
      - 'api/**'
  pull_request:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install tools
      run: pip install pylint
    - name: Run lint
      run: pylint --rcfile=api/.pylintrc api
  
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install tools
      run: pip install pytest
    - name: Run test
      run: pytest