on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.5'
    - name: Install poetry
      run: pip install poetry
    - name: Install dependencies
      working-directory: api
      run: poetry install
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: 4.4.5
    - name: Lint
      working-directory: api
      run: poetry run task lint
    - name: Tests
      working-directory: api
      run: poetry run task test
