on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install python
      uses: actions/setup-python@v4
    - name: Install poetry
      run: pip install poetry
    - name: Install dependencies
      working-directory: ./code
      run: poetry install
    - name: Lint
      working-directory: ./code
      run: poetry run task lint
    - name: Tests
      working-directory: ./code
      run: poetry run task test
