
name: Spell checking

on: push

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install tools
      run: sudo apt install aspell aspell-es aspell-en
    - name: Add allowed words
      run: python ./scripts/order_dict.py
    - name: Spell check
      run: sudo ./scripts/spellcheck.sh