name: Spell checking

on:
  push:
    branches:
      - master
  pull_request: 
    branches:
      - master

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install tools
      run: sudo apt install aspell aspell-es aspell-en
    - name: Spell check
      run: make spell-check