name: Spell checking

on:
  push:
    paths:
      - 'doc/**'

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install tools
      run: sudo apt install aspell aspell-es aspell-en
    - name: Spell check
      run: make spell-check