on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      working-directory: front
      run: npm install
    - name: Lint
      working-directory: front
      run: npm run lint
    - name: Tests
      working-directory: front
      run: npm run test
